services:
    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "blue-elephant" #Postgres's logo is an elephant :P
            POSTGRES_DB: "gift_list"
        ports:
            - "65432:5432" #Different port to not conflict with any possible real/default Postgres installation
